#ifndef TRACE_H
#define TRACE_H

typedef struct {
    bool run;
    unsigned period;
    unsigned nprio;
} trace_entry_t;

#define TINY_PERIOD 100000 
#define SMALL_PERIOD 240000
#define MEDIUM_PERIOD 750000
#define LARGE_PERIOD 1200000

const char light_models[MAX_THREADS][256] = {
    "models/model_16_4.txt",
    "models/model_32_3.txt",
    "models/model_16_4.txt",
    "models/model_32_3.txt",
};

const char heavy_models[MAX_THREADS][256] = {
    "models/model_48_4.txt",
    "models/model_64_3.txt",
    "models/model_48_4.txt",
    "models/model_64_3.txt",
};

const char mixed_models[MAX_THREADS][256] = {
    "models/model_16_4.txt",
    "models/model_32_3.txt",
    "models/model_48_4.txt",
    "models/model_64_3.txt",
};

unsigned light_deadlines[MAX_THREADS] = {
    TINY_PERIOD, SMALL_PERIOD, TINY_PERIOD, SMALL_PERIOD,
};

const trace_entry_t light_trace[][MAX_THREADS] = {
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.4 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.5 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.6 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.7 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.8 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.0 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.1 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.4 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.5 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.6 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.7 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.8 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.9 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.0 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.1 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.1 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.0 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.9 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.8 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.7 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.6 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.5 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.4 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.4 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.6 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.8 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.0 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.8 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.4 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 2.0 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.6 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 3.3 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {true, 1.2 * SMALL_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {true, 1.2 * TINY_PERIOD, 1}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {true, 1 * SMALL_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, TINY_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
};

unsigned heavy_deadlines[MAX_THREADS] = {
    MEDIUM_PERIOD, LARGE_PERIOD, MEDIUM_PERIOD, LARGE_PERIOD,
};

const trace_entry_t heavy_trace[][MAX_THREADS] = {
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.4 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.5 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.6 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.7 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.8 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.0 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.1 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.4 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.5 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.6 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.7 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.8 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.9 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.0 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.1 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.1 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.0 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.9 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.8 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.7 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.6 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.5 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.4 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.4 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.6 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.8 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.0 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.8 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.4 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 2.0 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.6 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 3.3 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {true, 1.2 * LARGE_PERIOD, 1} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {true, 1.2 * MEDIUM_PERIOD, 1}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {true, 1 * LARGE_PERIOD, 1}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
    { {true, MEDIUM_PERIOD, 1}, {false, 0, 6}, {false, 0, 6}, {false, 0, 6} },
};

unsigned mixed_deadlines[MAX_THREADS] = {
    TINY_PERIOD, SMALL_PERIOD, MEDIUM_PERIOD, LARGE_PERIOD,
};

const trace_entry_t mixed_trace[][MAX_THREADS] = {
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 3 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 3 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 3 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 2 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 1 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 1 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 2 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 3 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 1 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {true, 1 * MEDIUM_PERIOD, 1}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
    { {true, TINY_PERIOD, 1}, {true, SMALL_PERIOD, 1}, {false, 0, 6}, {true, LARGE_PERIOD, 1} },
};

#endif // TRACE_H
