#ifndef TRACE_H
#define TRACE_H

typedef struct {
    bool run;
    unsigned period;
    unsigned nprio;
} trace_entry_t;

#define MEDIUM_PERIOD 286000

#define N_THREADS 2

const char model_list[N_THREADS][256] = {
    "models/model_48_2.txt",
    "models/model_48_2.txt",
};

const trace_entry_t trace[][N_THREADS] = {
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 2.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 2.9 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 3.9 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 5.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 6.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 5.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 3.9 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 2.9 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 2.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.5 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
    { {true, 0, 1}, {true, 1.1 * MEDIUM_PERIOD, 1} },
};

#endif // TRACE_H
