ACCEL_FILES+=$(ACCEL_DIR)/gemm/gemm_def.c
CFLAGS+=-I$(ACCEL_DIR)/gemm

ESP_INCDIR += -I$(ESP_ROOT)/accelerators/stratus_hls/gemm_stratus/sw/linux/include
ESP_INCDIR += -I$(ESP_ROOT)/accelerators/stratus_hls/gemm_sm_stratus/sw/linux/include
